PUC_COLOMBIA = [
    {"code": "1", "name": "ACTIVO", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 1},
    {"code": "11", "name": "DISPONIBLE", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1105", "name": "Caja", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1110", "name": "Bancos", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3},
    {"code": "111005", "name": "Bancos - Moneda Nacional", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 4, "accepts_movements": True},
    {"code": "1120", "name": "Cuentas de Ahorro", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "12", "name": "INVERSIONES", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1205", "name": "Acciones", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "13", "name": "DEUDORES", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1305", "name": "Clientes Nacionales", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True, "third_party_required": True},
    {"code": "1310", "name": "Clientes del Exterior", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True, "third_party_required": True},
    {"code": "1355", "name": "Anticipo de Impuestos", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1365", "name": "Cuentas por Cobrar a Trabajadores", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "14", "name": "INVENTARIOS", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1405", "name": "Inventario de Mercancías", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1430", "name": "Materias Primas", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1460", "name": "Productos en Proceso", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "15", "name": "PROPIEDADES, PLANTA Y EQUIPO", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1504", "name": "Terrenos", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1506", "name": "Construcciones y Edificaciones", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1512", "name": "Maquinaria y Equipo", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1516", "name": "Equipo de Oficina", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1520", "name": "Equipo de Computación", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1524", "name": "Vehículos", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1580", "name": "Depreciación Acumulada", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "16", "name": "INTANGIBLES", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1605", "name": "Licencias", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "1610", "name": "Software", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "17", "name": "DIFERIDOS", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1705", "name": "Gastos Pagados por Anticipado", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "18", "name": "OTROS ACTIVOS", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1805", "name": "Cargos Diferidos", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "19", "name": "VALORIZACIONES", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 2},
    {"code": "1905", "name": "Valorización de Inversiones", "account_type": "Activo", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},

    {"code": "2", "name": "PASIVO", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 1},
    {"code": "21", "name": "OBLIGACIONES FINANCIERAS", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "2105", "name": "Bancos Nacionales", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2110", "name": "Bancos del Exterior", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "22", "name": "PROVEEDORES", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "2205", "name": "Proveedores Nacionales", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True, "third_party_required": True},
    {"code": "2210", "name": "Proveedores del Exterior", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True, "third_party_required": True},
    {"code": "23", "name": "CUENTAS POR PAGAR", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "2305", "name": "Cuentas Corrientes Comerciales", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2335", "name": "Costos y Gastos por Pagar", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2360", "name": "Retención en la Fuente", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2365", "name": "Impuesto a las Ventas por Pagar", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2370", "name": "IVA por Pagar", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2375", "name": "Retención de ICA", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2380", "name": "Aportes a Seguridad Social por Pagar", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "24", "name": "IMPUESTOS POR PAGAR", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "2405", "name": "Impuesto de Renta por Pagar", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2410", "name": "IVA por Pagar", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2415", "name": "ICA por Pagar", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "25", "name": "OBLIGACIONES LABORALES", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "2505", "name": "Salarios por Pagar", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2510", "name": "Cesantías", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2515", "name": "Intereses sobre Cesantías", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2520", "name": "Prima de Servicios", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "2525", "name": "Vacaciones", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "26", "name": "PASIVOS ESTIMADOS Y PROVISIONES", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "2605", "name": "Provisiones Varias", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "27", "name": "DIFERIDOS", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "2705", "name": "Ingresos Recibidos por Anticipado", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "28", "name": "OTROS PASIVOS", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "2805", "name": "Anticipos Recibidos", "account_type": "Pasivo", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},

    {"code": "3", "name": "PATRIMONIO", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 1},
    {"code": "31", "name": "CAPITAL SOCIAL", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "3105", "name": "Capital Suscrito y Pagado", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "3110", "name": "Aportes Sociales", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "32", "name": "SUPERÁVIT DE CAPITAL", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "3205", "name": "Superávit de Capital", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "33", "name": "RESERVAS", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "3305", "name": "Reservas Legales", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "3310", "name": "Reservas Estatutarias", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "34", "name": "REVALORIZACIÓN DEL PATRIMONIO", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "3405", "name": "Ajustes por Inflación", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "36", "name": "RESULTADOS DEL EJERCICIO", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "3605", "name": "Utilidad del Ejercicio", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "3610", "name": "Pérdida del Ejercicio", "account_type": "Patrimonio", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "37", "name": "RESULTADOS DE EJERCICIOS ANTERIORES", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 2},
    {"code": "3705", "name": "Utilidades Acumuladas", "account_type": "Patrimonio", "nature": "Acreedora", "account_class": "Real", "level": 3, "accepts_movements": True},
    {"code": "3710", "name": "Pérdidas Acumuladas", "account_type": "Patrimonio", "nature": "Deudora", "account_class": "Real", "level": 3, "accepts_movements": True},

    {"code": "4", "name": "INGRESOS", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 1},
    {"code": "41", "name": "INGRESOS OPERACIONALES", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 2},
    {"code": "4105", "name": "Comercio al por Mayor y al por Menor", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "4110", "name": "Venta de Productos", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "4115", "name": "Venta de Servicios", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "4120", "name": "Ingresos por Comisiones", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "42", "name": "INGRESOS NO OPERACIONALES", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 2},
    {"code": "4205", "name": "Rendimientos Financieros", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "4210", "name": "Otros Ingresos", "account_type": "Ingreso", "nature": "Acreedora", "account_class": "Nominal", "level": 3, "accepts_movements": True},

    {"code": "5", "name": "GASTOS", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 1},
    {"code": "51", "name": "GASTOS OPERACIONALES DE ADMINISTRACIÓN", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 2},
    {"code": "5105", "name": "Gastos de Personal", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "510506", "name": "Sueldos", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 4, "accepts_movements": True},
    {"code": "510512", "name": "Prestaciones Sociales", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 4, "accepts_movements": True},
    {"code": "510518", "name": "Aportes a Seguridad Social", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 4, "accepts_movements": True},
    {"code": "5110", "name": "Honorarios", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5115", "name": "Impuestos", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5120", "name": "Arrendamientos", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5125", "name": "Servicios Públicos", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5130", "name": "Mantenimiento y Reparaciones", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5135", "name": "Depreciaciones", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5140", "name": "Amortizaciones", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5145", "name": "Publicidad y Propaganda", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5150", "name": "Seguros", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5155", "name": "Gastos de Viaje", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5160", "name": "Gastos Legales", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5165", "name": "Papelería y Útiles de Oficina", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5170", "name": "Comunicaciones", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "52", "name": "GASTOS OPERACIONALES DE VENTAS", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 2},
    {"code": "5205", "name": "Gastos de Personal Ventas", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5210", "name": "Comisiones en Ventas", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "53", "name": "GASTOS FINANCIEROS", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 2},
    {"code": "5305", "name": "Gastos Bancarios", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5310", "name": "Intereses", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "54", "name": "IMPUESTOS Y CONTRIBUCIONES", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 2},
    {"code": "5405", "name": "Impuesto de Renta", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "5410", "name": "ICA", "account_type": "Gasto", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},

    {"code": "6", "name": "COSTOS", "account_type": "Costo", "nature": "Deudora", "account_class": "Nominal", "level": 1},
    {"code": "61", "name": "COSTO DE VENTAS", "account_type": "Costo", "nature": "Deudora", "account_class": "Nominal", "level": 2},
    {"code": "6105", "name": "Costo de Venta de Productos", "account_type": "Costo", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "6110", "name": "Costo de Venta de Servicios", "account_type": "Costo", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "62", "name": "COSTOS OPERACIONALES", "account_type": "Costo", "nature": "Deudora", "account_class": "Nominal", "level": 2},
    {"code": "6205", "name": "Mano de Obra Directa", "account_type": "Costo", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "6210", "name": "Materiales Directos", "account_type": "Costo", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},
    {"code": "6220", "name": "Costos Indirectos", "account_type": "Costo", "nature": "Deudora", "account_class": "Nominal", "level": 3, "accepts_movements": True},

    {"code": "7", "name": "CUENTAS DE ORDEN DEUDORAS", "account_type": "Cuenta de Orden", "nature": "Deudora", "account_class": "Orden", "level": 1},
    {"code": "71", "name": "CUENTAS DE ORDEN DEUDORAS", "account_type": "Cuenta de Orden", "nature": "Deudora", "account_class": "Orden", "level": 2},
    {"code": "7105", "name": "Garantías Recibidas", "account_type": "Cuenta de Orden", "nature": "Deudora", "account_class": "Orden", "level": 3, "accepts_movements": True},
    {"code": "7110", "name": "Documentos Descontados", "account_type": "Cuenta de Orden", "nature": "Deudora", "account_class": "Orden", "level": 3, "accepts_movements": True},
    {"code": "7120", "name": "Bienes en Custodia", "account_type": "Cuenta de Orden", "nature": "Deudora", "account_class": "Orden", "level": 3, "accepts_movements": True},

    {"code": "8", "name": "CUENTAS DE ORDEN ACREEDORAS", "account_type": "Cuenta de Orden", "nature": "Acreedora", "account_class": "Orden", "level": 1},
    {"code": "81", "name": "CUENTAS DE ORDEN ACREEDORAS", "account_type": "Cuenta de Orden", "nature": "Acreedora", "account_class": "Orden", "level": 2},
    {"code": "8105", "name": "Garantías Otorgadas", "account_type": "Cuenta de Orden", "nature": "Acreedora", "account_class": "Orden", "level": 3, "accepts_movements": True},
    {"code": "8110", "name": "Documentos Re-descontados", "account_type": "Cuenta de Orden", "nature": "Acreedora", "account_class": "Orden", "level": 3, "accepts_movements": True},
]
