# 02dbdb202e3f_add_image_url_to_products.py
# Propósito: Migración: añadir columna image_url a productos

"""add_image_url_to_products

Revision ID: 02dbdb202e3f
Revises: 
Create Date: 2026-06-10 11:35:42.094252
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '02dbdb202e3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
